<a href="https://colab.research.google.com/github/olegggwp/code_keyboard_test/blob/master/%D1%82%D0%B5%D0%BD%D0%B7%D0%BE%D1%80%D1%8B_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://drive.google.com/drive/folders/1ajK2MzfnE2qVVmvAMxV4eO_Orta-XR4W?usp=sharing -- примеры условий + решение 6-й


[adv](https://t.me/olegggwpmeme)




In [ ]:
  import numpy as np
  import itertools

In [ ]:
def tensor2d_gayout(a):
  print("[", end='')
  ass = np.shape(a)
  for x in range(ass[0]):
    for y in range(ass[1]):
      print(a[x, y], end = '')
      if not(y == ass[1]-1) :
        print("", end=', ')
    if x < ass[0]-1:
      print(";")
  print("]", end='')

# example = np.arange(9).reshape((3, 3))
# print(example)
# tensor2d_gayout(example)

def toFixed(numObj, digits=0):
    return f"{numObj:.{digits}f}"

def tensor3d_gayout(a):
  print("[", end='')
  ass = np.shape(a)
  for y in range(ass[1]):
    for x in range(ass[0]):
      for z in range(ass[2]):
        print(toFixed(a[x, y, z], 2), end = '')
        if not(x == ass[0]-1 and z == ass[2]-1) :
          print("", end=', ')
    if y < ass[1]-1:
      print(";")
  print("]", end='')
# пример 
# example = np.arange(27).reshape((3, 3, 3))
# print(example)
# tensor3d_gayout(example)

def tensor_mul(a, b):
  rshape = np.shape(a) + np.shape(b)
  r = np.zeros(rshape)
  ita = [range(x) for x in np.shape(a)]
  itb = [range(x) for x in np.shape(b)]
  for ai in itertools.product(*ita):
    for bi in itertools.product(*itb):
      # print(a[ai], b[bi])
      r[ai + bi] = a[ai]*b[bi]
  return r

# пример
# a = np.array([1, -1, 0])
# b = np.arange(1,10).reshape((3, 3))
# print("a: ", a, sep = '\n')
# print("b: ", b, sep = '\n')
# print("c: ", tensor_mul(a, b), sep = '\n')
# tensor3d_gayout(tensor_mul(a, b))


# WARNING!: новая форма должна быть перестановкой старой,
# иначе поведение программы не предсказуемо
# [0, 2, 1] -- OK
def redefine_shape(ts, reord):
  oldshape = np.shape(ts)
  n = len(reord)
  new_shape = [oldshape[reord[i]] for i in range(n)]
  r = np.empty(tuple(new_shape))
  si = [range(x) for x in oldshape]
  for it in itertools.product(*si):
    nw_coord = [it[reord[i]] for i in range(n)]
    r[tuple(nw_coord)] = ts[it]
  return r
# пример
# ex = np.arange(6).reshape(2, 3)
# print(ex, len([1, 0]))
# print(redefine_shape(ex, [1, 0]))

def cool3dout(a):
  aa = redefine_shape(a, [2, 0, 1])
  tensor3d_gayout(aa)

------------------------------


## задача 1

In [ ]:
a = np.zeros((2, 2, 2, 2))

a[:,:,0,0] = [[-3, 2],
              [-3, -2]]
a[:,:,0,1] = [[0, 3],
              [4, -5]]
a[:,:,1,0] = [[-4, 1],
              [-5, 0]]
a[:,:,1,1] = [[5, 6],
              [6, -2]]

In [ ]:
x = [[-1, 1], [-5, -2], [-5, -4], [-5, -3]]

In [ ]:
sum = 0
for m in range(2):
  for k in range(2):
    for n in range(2):
      for j in range(2):
        sum += a[m, k, j, n] * x[0][m] * x[1][k] * x[2][n] * x[3][j] 


In [ ]:
print(sum)

357.0


## Задача 2

In [ ]:
a = np.zeros((2, 2, 2))

a[:,:,0] = [[1, -4],[6, 5]]
a[:,:,1] = [[1, 1], [5, -4]]

x = [[-5, -3], [0, 3], [-1, -2]]

In [ ]:
sum = 0
for i in range(2):
  for n in range(2):
    for m in range(2):
      sum += a[i, n, m] * x[0][i] * x[1][n] * x[2][m]
print(sum) 

-57.0


## Задача 3

In [ ]:
#_ 12 * e2 * f1 * f1 * f1
#_ -48 * e2 * f2 * f1 * f1
#_ 8 * e2 * f1 * f1 * f2
#_ -32 * e2 * f2 * f1 * f2

In [ ]:
#_ e2 * ( 12 f1 f1 f1  8 f1 f1 f2  -48 f2 f1 f1  -32 f2 f1 f2)

#_ e2 * ( 4 f1 f1 (3 f1 + 2 f2)  -16 f2 f1 (3 f1 + 2 f2))

#_ e2 * ( 4 f1 f1 -16 f2 f1 ) (3 f1 + 2 f2)

#_ 4 e2 * (1 f1 - 4 f2 ) * f1 * (3 f1 + 2 f2)




## задача 4

In [ ]:
## [4 3 1]  [-1 -3 1] [2, 1, -3]

## задача 5

In [ ]:
a = np.zeros((3, 3, 3))
a[:, :, 0] = [[3, 1, -7],
              [-1, 5, 3],
              [3, -7, -1]]
a[:, :, 1] = [[-3, 7, 7],
              [2, 2, -3],
              [-7, 8, -5]]

a[:, :, 2] = [[6, 3, 2],
              [7, 5, 8],
              [-7, 7, 3]]

# cool3dout(a)

e1 = np.array([[-1, -2, 1],
               [-1, -1, 0],
               [0, 1, 0]])

e2 = np.array([[1, -1, -2],
               [-1, 2, 1],
               [0, -1, 2]])


s = np.dot(np.linalg.inv(e2), e1)
t = np.dot(np.linalg.inv(e1), e2)

# a'(IX,Y) = a(jn,i) * s(I,j) *s(X,n)*t(i,Y)

a1 = np.tensordot(a, s, axes = ([0], [1]))
a2 = np.tensordot(a1, s, axes = ([0], [1]))
a3 = np.tensordot(a2, t, axes = ([0], [0]))


cool3dout(a3)

[4335.0, 1983.0, 895.0, -7937.0, -3652.0, -1660.0, -4245.0, -1894.0, -820.0;
1937.0, 887.0, 399.0, -3572.0, -1645.0, -744.0, -1841.0, -822.0, -357.0;
875.0, 399.0, 181.0, -1587.0, -729.0, -332.0, -890.0, -394.0, -174.0]

In [ ]:
a = np.zeros((3, 3, 3))
a[:, :, 0] = [[1, 0, -6],
              [1, -1, 4],
              [0, -1, 5]]

a[:, :, 1] = [[-1, 7, 6],
              [-5, -7, 0],
              [-5, -5, -8]]

a[:, :, 2] = [[1, 0, 1],
              [-4, -5, 5],
              [-3, 0, -3]]

# cool3dout(a)

e1 = np.array([[-1, -2, -1],
               [-1, -1, 0],
               [0, -1, 0]])

e2 = np.array([[-1, -1, -1],
               [-1, 0, -2],
               [3, 2, 5]])


s = np.dot(np.linalg.inv(e2), e1)
t = np.dot(np.linalg.inv(e1), e2)

# a'(IX,Y) = a(jn,i) * s(I,j) *s(X,n)*t(i,Y)

a1 = np.tensordot(a, s, axes = ([0], [1]))
a2 = np.tensordot(a1, s, axes = ([0], [1]))
a3 = np.tensordot(a2, s, axes = ([0], [1]))

print(a3)
cool3dout(a3)

[[[-22073.   7937.  10351.]
  [  9197.  -3301.  -4313.]
  [  9802.  -3527.  -4596.]]

 [[  7112.  -2537.  -3340.]
  [ -3025.   1077.   1421.]
  [ -3135.   1119.   1472.]]

 [[ 10771.  -3882.  -5049.]
  [ -4461.   1605.   2091.]
  [ -4794.   1729.   2247.]]]
[-22073.00, 9197.00, 9802.00, 7937.00, -3301.00, -3527.00, 10351.00, -4313.00, -4596.00;
7112.00, -3025.00, -3135.00, -2537.00, 1077.00, 1119.00, -3340.00, 1421.00, 1472.00;
10771.00, -4461.00, -4794.00, -3882.00, 1605.00, 1729.00, -5049.00, 2091.00, 2247.00]

# Тензоры 4

## Задача 4

In [ ]:
a = np.zeros((2, 2, 2))

a[:,:,0] = [[-6, -6], [0, 0]]

a[:,:,1] = [[4, -5], [-2, -3]]

b = redefine_shape(a, [1, 0, 2])
cool3dout(b)

[-6.0, 0.0, 4.0, -2.0;
-6.0, 0.0, -5.0, -3.0]

## Задача 5

In [ ]:
a = np.zeros((3, 3, 3))

a[:,:,0] = [[2, -6, 1],
            [4, 2, 5],
            [-1, 0, 2]]

a[:,:,1] = [[-5, 0, 1],
            [4, -4, -3],
            [-2, -5, -3]]

a[:,:,2] = [[5, 3, -4],
            [-5, 6, 4],
            [5, -3, 5]]

b = redefine_shape(a, [1, 0, 2])
cool3dout(b)

[2.0, 4.0, -1.0, -5.0, 4.0, -2.0, 5.0, -5.0, 5.0;
-6.0, 2.0, 0.0, 0.0, -4.0, -5.0, 3.0, 6.0, -3.0;
1.0, 5.0, 2.0, 1.0, -3.0, -3.0, -4.0, 4.0, 5.0]

# Тензоры 4

In [ ]:
def oodd(p):
  n = len(p)
  cnt = 0
  for i in range(n):
    for j in range(i, n):
      if p[i] > p[j]:
        cnt +=1
  return cnt%2

In [ ]:
def fact(n):
  fuc=1 
  for i in range(2,n+1):
     fuc=fuc*i
  return fuc
## симмертизвция
def symm(t):
  shp = [i for i in range(len(np.shape(t)))]
  sperm = [i for i in itertools.permutations(shp)]
  res = np.zeros(np.shape(t))
  for i in range(len(sperm)):
    res += redefine_shape(t, sperm[i])
  x = fact(len(np.shape(t)))
  res /= x
  return res

def asymm(t, fixed):
  shp = [i for i in range(len(np.shape(t)))]
  sperm = []
  for i in itertools.permutations(shp):
    if all(i[j] == j for j in fixed) or len(fixed) == 0:
      sperm.append(i)
  
  res = np.zeros(np.shape(t))
  for i in sperm:
    res += ((-1)**oodd(i))*redefine_shape(t, i)
  res /= len(sperm)
  return res

## задача 7

In [ ]:
a = np.zeros((2,2,2))

a[:,:,0] = [[4, 5], [2, 5]]

a[:,:,1] = [[-5,-2],[2, -4]]

b = symm(a)
cool3dout(b)

[4.0, 0.6666666666666666, 0.6666666666666666, 1.6666666666666667;
0.6666666666666666, 1.6666666666666667, 1.6666666666666667, -4.0]

## 6

In [ ]:
a = np.zeros((3, 3, 3))

a[:,:,0] = [[2, -4, -4], [5, 4, -5], [-2, 2, -3]]

a[:,:,1] = [[0, -4, 4], [5, -3, 4], [4, 6, 1]]

a[:,:,2] = [[2, -6,4],[1, 5, -4], [4, 0, 3]]

b = asymm(a, [2])

cool3dout(b)

[0.0, -4.5, -1.0, 0.0, -4.5, 0.0, 0.0, -3.5, 0.0;
4.5, 0.0, -3.5, 4.5, 0.0, -1.0, 3.5, 0.0, -2.0;
1.0, 3.5, 0.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0]

In [ ]:
def outer_mul(u, v):
  p = len(np.shape(u))
  r = len(np.shape(v))
  a = tensor_mul(u, v)
  a = asymm(a, [])
  a *= fact(p+r)
  a /= (fact(p)*fact(r))
  return a

In [ ]:
a = np.array([0, -6, 2])
b = np.array([[0, -5, 4],[0, -2, 6], [-5, -1, -1]])
c = outer_mul(a, b)
cool3dout(c)
# print("")
# print(redefine_shape(c,[1, 2, 0]))

[0.0, 0.0, 0.0, 0.0, 0.0, -22.0, 0.0, 22.0, 0.0;
0.0, 0.0, 22.0, 0.0, 0.0, 0.0, -22.0, 0.0, 0.0;
0.0, -22.0, 0.0, 22.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [ ]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
# c = np.array([0, 0, 1])
dd = outer_mul(a, b)
# d = outer_mul(dd, c)
print(dd)

[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]


In [ ]:
a1 = np.array([0, 2, -3])
a2 = np.array([1, 4, 0])
a3 = np.array([-2, -3, 2])
a = tensor_mul(a2, a1)
# print(a)
b = tensor_mul(a, a3)
cool3dout(b)

[-0.0, -4.0, 6.0, -0.0, -6.0, 9.0, 0.0, 4.0, -6.0;
-0.0, -16.0, 24.0, -0.0, -24.0, 36.0, 0.0, 16.0, -24.0;
-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0]